### ISSUE TITLE
NcSpace overrides BlSpace's API

### ISSUE THREAD

**Issue by tinchodias** [lucretiomsp/nature-of-code-pharo#1]
NcSpace>>#center

**Comment by tinchodias** [comment]
Sorry, I pressed "enter" by mistake and the issue was submitted. I didn't know that!

What I tried to say is `BlSpace>>center` has a meaning, and `NcSpace>>center` overrides it without another meaning. This is not a good idea / practice. This sometimes happens by mistake, probably it's the case:

<img width="663" alt="Screenshot 2024-12-09 at 12 08 32" src="https://github.com/user-attachments/assets/486a7935-93dc-4b5e-8f51-c5c93c1967c1">

**Comment by lucretiomsp** [comment]
thanks Martin! I will fix that
peace.
d

**Comment by tinchodias** [comment]
I'm looking for a good answer to your question in Discord about the center.
I loaded the code and tested it. In any case I see the walker stepping on the top left corner.
In one side, I came back to and old issue about centering: https://github.com/pharo-graphics/Bloc/issues/249
But I'm still not sure what's the correct answer for your concrete case.
Maybe use the transformations.

**Comment by lucretiomsp** [comment]
thank you very much for the help. I am working on more examples. if you see
anything bad in my code I am very happy to fix it :)
peace.
d
